version: '3.8'

services:
  db:
    image: postgres:16
    container_name: uac-db-prod
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: uac_rdc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: uac-api-prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_TYPE=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=admin123
      - DATABASE_NAME=uac_rdc
      - NODE_ENV=production
      - JWT_SECRET=TaCleSecrete
    depends_on:
      - db

volumes:
  postgres_data:
